#! /bin/sh

# @HEADER
# @HEADER


set -x
#libtoolize
# Only run aclocal if we need to create aclocal.m4
aclocal -I config 
# autoheader is smart and doesn't change anything unless it's necessary
autoheader 
automake --foreign --add-missing --copy
autoconf
