#!/bin/sh

##################################################################
#
# Configuration of Trilinos for use with Sundance
#
##################################################################

#CXXFLAGS="-g -pg -fprofile-arcs -ftest-coverage -O0 -Wreturn-type" \

BUILD_DIR=`pwd`

../configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-g -pg -O0 -Wall" \
CFLAGS="-g -pg -O0 -Wall" \
--with-libs="-lexpat -lumfpack -lamd" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended \
--enable-teuchos-complex --enable-teuchos-abc --enable-teuchos-expat \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--disable-aztecoo-thyra \
--disable-epetra-thyra \
--disable-amesos-thyra \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--prefix=$BUILD_DIR


