#!/bin/sh

##################################################################
#
# Configuration of Trilinos for use with Sundance
#
##################################################################


BUILD_DIR=`pwd`



../configure \
CXXFLAGS="-O3 -finline-functions -funroll-loops -Wall" \
--with-libs="-lumfpack -lamd" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended \
--enable-teuchos-complex \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--enable-aztecoo-thyra \
--enable-epetra-thyra \
--enable-epetraext-thyra \
--enable-amesos-thyra \
--enable-ifpack-thyra \
--enable-ml-thyra \
--enable-stratimikos \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--config-cache \
--prefix=$BUILD_DIR

