#!/bin/sh

##################################################################
#
# Configuration of Trilinos for use with Sundance
#
##################################################################


BUILD_DIR=`pwd`
TRILINOS_SRC_DIR="/home/kevin/Software/Trilinos/trilinos-8.0.4"

$TRILINOS_SRC_DIR/configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-g -O0 -Wall" \
--with-libs="-lumfpack -lamd" \
--disable-default-packages \
--enable-teuchos --enable-teuchos-extended --enable-teuchos-abc \
--enable-teuchos-complex \
--enable-thyra \
--disable-thyra-tests \
--disable-thyra-examples \
--enable-aztecoo-thyra \
--enable-epetra-thyra \
--enable-amesos-thyra \
--enable-ifpack-thyra \
--enable-ml-thyra \
--enable-stratimikos \
--enable-epetra \
--enable-epetraext \
--enable-ml \
--disable-ml-examples \
--enable-aztecoo \
--enable-ifpack \
--enable-nox \
--disable-loca \
--enable-amesos \
--enable-amesos-umfpack \
--enable-moocho \
--enable-moocho-thyra \
--with-gnumake \
--with-install="/usr/bin/install -c -p" \
--config-cache \
--prefix=$BUILD_DIR

