#!/bin/sh

BUILD_DIR=`pwd`

../configure  \
CXX="/usr/local/intel/bin/icc" \
CC="/usr/local/intel/bin/icc" \
CXXFLAGS="-O3 -finline-functions -cxxlib-gcc -I/usr/local/include" \
--with-ldflags="-L/usr/local/intel/lib" \
FLIBS="-lfrtbegin -lg2c -lm -lgcc_s -lstdc++ -lgcc" \
--enable-mpi --with-mpi-libs="-lmpich -lpmpich" \
--with-trilinos=$HOME/Projects/Trilinos/LINUX-INTEL-OPT \
--prefix=$BUILD_DIR

