#!/bin/sh

BUILD_DIR=`pwd`

../configure CXXFLAGS="-O3 -finline-functions -funroll-loops" \
--enable-mpi --with-mpi-compilers \
--with-trilinos=$HOME/Projects/Trilinos/LINUX-OPT \
--prefix=$BUILD_DIR

