#!/bin/sh

# @HEADER
# ************************************************************************
# 
#                              Sundance
#                 Copyright (2005) Sandia Corporation
# 
# Copyright (year first published) Sandia Corporation.  Under the terms 
# of Contract DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government 
# retains certain rights in this software.
# 
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.
#  
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#                                                                                 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA                                                                                
# Questions? Contact Kevin Long (krlong@sandia.gov), 
# Sandia National Laboratories, Livermore, California, USA
# 
# ************************************************************************
# @HEADER


# This compiles (sort of) Sundance on Rob Kirby's MacBook Pro.
# see the trilinos-scripts/mac_intel_serial for more details on
# what software I'm using.

# currently this successfully builds PySundance but is unable to
# link C++ Sundance executables.  I will update this file if ever
# I get that fixed.

BUILD_DIR=`pwd`

../configure --disable-mpi \
CXXFLAGS="-Wall" \
--with-trilinos=/Users/kirby/trilinos-6.0.17/mac_intel_serial \
--with-install="/usr/bin/install -c -p" \
--enable-python \
--disable-cxxtests \
--enable-cxxexamples \
--disable-lowleveltests \
--prefix=$BUILD_DIR

