#!/bin/sh

# @HEADER
# ************************************************************************
#
#                              Sundance
#                 Copyright (2005) Sandia Corporation
#
# Copyright (year first published) Sandia Corporation.  Under the terms
# of Contract DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government
# retains certain rights in this software.
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#

# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

# Questions? Contact Kevin Long (krlong@sandia.gov),
# Sandia National Laboratories, Livermore, California, USA
#
# ************************************************************************
# @HEADER

###--with-fiat=$HOME/Projects/FIAT/BUILD \
#--with-sundials=$HOME/Software/Math/sundials/LINUX-OPT \
#--with-fiat=$HOME/Projects/fiat++/BUILD \

BUILD_DIR=`pwd`
TRILINOS_BUILD_DIR=/scratch3/krlong/Trilinos/GCC-MPICH
SUNDANCE_SRC_DIR=$HOME/Software/Sundance

$SUNDANCE_SRC_DIR/configure --enable-mpi --with-mpi-compilers \
CXXFLAGS="-fpic -Wall -O3 -finline-functions -funroll-loops" \
CFLAGS="-fpic -Wall -O3" \
FFLAGS="-fpic -Wall -O3" \
--with-trilinos=$TRILINOS_BUILD_DIR \
--with-install="/usr/bin/install -c -p" \
--enable-python \
--disable-cxxtests \
--disable-cxxexamples \
--disable-lowleveltests \
--prefix=$BUILD_DIR
