SET(LIB_REQUIRED_DEP_PACKAGES
  Teuchos Epetra EpetraExt Thyra Amesos AztecOO Ifpack ML Anasazi Belos Stratimikos NOX Intrepid)
SET(LIB_OPTIONAL_DEP_PACKAGES MOOCHO)

SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS ExodusII MPI)

SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS ExodusII MPI)

