SET(LIB_REQUIRED_DEP_PACKAGES
  Teuchos Epetra Thyra Amesos AztecOO Ifpack ML Anasazi NOX )
SET(LIB_OPTIONAL_DEP_PACKAGES MOOCHO)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
